<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Location_ctl00MainContentrdcLocation</name>
   <tag></tag>
   <elementGuidId>5f8604b2-39f2-4048-b697-9af526e8e616</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_rdcLocation_Input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_rdcLocation_Input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e62f80d1-61be-40e3-a40a-f62509ef6d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$rdcLocation</value>
      <webElementGuid>c7ea1dd4-8fc9-4c97-9b18-523903e49ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c4a30b6-12c6-4a4e-899b-3cdf7b056cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rcbInput radPreventDecorate</value>
      <webElementGuid>864da4d6-1f5a-492b-a8fc-eb74a7d8a31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_rdcLocation_Input</value>
      <webElementGuid>375c6e6d-334d-4622-aee8-032ac1b3a5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>All items check</value>
      <webElementGuid>17ac5b74-aa78-482b-a2bd-5ce9518be941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dfd9113f-1b11-44be-90e0-795372635a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_rdcLocation_Input&quot;)</value>
      <webElementGuid>68ad68b8-fdbd-4c1e-8ccf-a71ab2ae99cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_rdcLocation_Input']</value>
      <webElementGuid>7a37457c-e3c4-46a6-97d9-0c26d8fe35f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_MainContent_rdcLocation']/span/input</value>
      <webElementGuid>c616de2c-47f1-44a0-8b4e-e12d6548536d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span/input</value>
      <webElementGuid>2dddd99c-e767-4606-b88c-eef0b40b4e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainContent$rdcLocation' and @type = 'text' and @id = 'ctl00_MainContent_rdcLocation_Input']</value>
      <webElementGuid>1198f691-e987-4fde-9aef-7efc7e23c2a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
