<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Agency_ctl00MainContentradcomAgency</name>
   <tag></tag>
   <elementGuidId>b9deff2e-c904-4b8e-8e52-18e33d65bc46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_radcomAgency_Input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_radcomAgency_Input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6402748a-c0d0-42a7-b79d-599a06846db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$radcomAgency</value>
      <webElementGuid>a0324ca8-1ee2-46c1-b771-cb5446e03a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3df4e66-7e34-4d7f-9c4b-080e658ec3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rcbInput radPreventDecorate</value>
      <webElementGuid>417f2d7e-ff71-44e6-91c6-a572ae09e928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_radcomAgency_Input</value>
      <webElementGuid>7cba09ff-1a90-4ffe-9485-7b351631c3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>All items check</value>
      <webElementGuid>1caff3ca-c6a9-4d0e-8cac-0f0e92daf4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>312383b9-a6f3-4567-8474-a3fb9639812a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_radcomAgency_Input&quot;)</value>
      <webElementGuid>f02e6857-0b20-49e8-a847-9af41dba039e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_radcomAgency_Input']</value>
      <webElementGuid>b4323811-38de-4f53-90e1-4abe9f878639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_MainContent_radcomAgency']/span/input</value>
      <webElementGuid>7381e18b-d4c3-4274-85e1-26dce0cadd91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span/input</value>
      <webElementGuid>e9a1d634-67d6-45c6-b459-6282a32affac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainContent$radcomAgency' and @type = 'text' and @id = 'ctl00_MainContent_radcomAgency_Input']</value>
      <webElementGuid>4543940f-6d57-4a0d-8b8e-a6bcb1a98ebb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
