<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Department_ctl00MainContentrdcDepartment</name>
   <tag></tag>
   <elementGuidId>d7281d52-8142-4a8d-8ebe-ffd74816a2c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_rdcDepartment_Input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_rdcDepartment_Input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3328fc10-6a6b-468e-b8fc-ab8a5e4485b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$rdcDepartment</value>
      <webElementGuid>c99ef256-c2f0-4997-bd57-8bfdb5f5ac86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc6192e0-9324-4751-95a6-b70417854185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rcbInput radPreventDecorate</value>
      <webElementGuid>653df380-96c1-4a03-85f0-92dc1184b76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_rdcDepartment_Input</value>
      <webElementGuid>71582a68-47d1-43df-8b91-a7690d0e3aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>All items check</value>
      <webElementGuid>5436d56e-0d45-4745-9463-ac653a939bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c60c6253-a747-4915-be83-b06bbdd020ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_rdcDepartment_Input&quot;)</value>
      <webElementGuid>e6168166-eaf5-43c2-adfe-4ad023b99368</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_rdcDepartment_Input']</value>
      <webElementGuid>0d12c789-8ccd-467f-a681-bce40d7f869d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_MainContent_rdcDepartment']/span/input</value>
      <webElementGuid>1ad0195b-bb8e-4b7d-8824-5d7396123ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/span/input</value>
      <webElementGuid>fe4f4ca7-9af9-4a5c-8401-6afa7263828b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainContent$rdcDepartment' and @type = 'text' and @id = 'ctl00_MainContent_rdcDepartment_Input']</value>
      <webElementGuid>0d8898bb-01a6-48a1-bdf6-8fb72037793a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
