<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Department_ctl00_MainContent_rdcDepart_f9d26a</name>
   <tag></tag>
   <elementGuidId>22e35971-59c9-432c-9fd3-29e43c3b374b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_MainContent_rdcDepartment_Arrow']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_rdcDepartment_Arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f4773db3-8c4c-453e-b3e4-ba7539b97e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_rdcDepartment_Arrow</value>
      <webElementGuid>929a00a1-de88-446a-8eb3-cf17dd4c3993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-font-icon t-i-arrow-down</value>
      <webElementGuid>3d1c01bb-9c41-49d3-9323-4e890de1800e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_rdcDepartment_Arrow&quot;)</value>
      <webElementGuid>3ae636e1-bd87-414a-b71e-21c7d9a09f03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_MainContent_rdcDepartment_Arrow']</value>
      <webElementGuid>b2e7c202-7237-4bf7-8e6e-58aeb7909ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_MainContent_rdcDepartment']/span/button/span</value>
      <webElementGuid>0d77068d-57ba-42b3-be1d-2590ef18f700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/span/button/span</value>
      <webElementGuid>612390b3-0404-48aa-b178-00baee447e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_MainContent_rdcDepartment_Arrow']</value>
      <webElementGuid>dbd244ae-755c-4cab-ac15-9bcc30ce2254</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
