<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Location_ctl00_MainContent_rdcLocation_Arrow</name>
   <tag></tag>
   <elementGuidId>6a8440a5-0808-440a-a8cc-d5308bf12e31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_MainContent_rdcLocation_Arrow']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_rdcLocation_Arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0c86e755-ffec-471d-bc79-273f5feda8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_rdcLocation_Arrow</value>
      <webElementGuid>7f6f49c0-8852-440f-96bf-afa52ce43cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-font-icon t-i-arrow-down</value>
      <webElementGuid>0435bcd5-d231-4766-a9a6-a7a14ed03ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_rdcLocation_Arrow&quot;)</value>
      <webElementGuid>010a2e7f-0487-4cb9-814f-ffe0e7122e2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_MainContent_rdcLocation_Arrow']</value>
      <webElementGuid>114f8e4c-ba6d-467a-9f98-a527af51b7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_MainContent_rdcLocation']/span/button/span</value>
      <webElementGuid>45e410fe-5ede-4888-b8dd-2f7fe85d652e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span/button/span</value>
      <webElementGuid>67595d6b-8328-48b6-a470-92860e9978c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_MainContent_rdcLocation_Arrow']</value>
      <webElementGuid>c2f6bdea-456e-4012-a7ed-cafb763345bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
