<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Agency</name>
   <tag></tag>
   <elementGuidId>ac91f59b-a5f0-4813-8717-40222967820c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_MenuUserCntrl1_RadMenu1']/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.rmLink.rmRootLink.rmExpand.rmExpandDown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c6dda765-4203-4ff8-84f2-a78cba72d83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rmLink rmRootLink rmExpand rmExpandDown</value>
      <webElementGuid>b92c9808-23ce-4f14-a5d6-4d55ad45da04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/DashBoard.aspx#</value>
      <webElementGuid>0dc8d823-c65a-4abb-bed3-1f6c287ec539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agency</value>
      <webElementGuid>15e52ab5-3cdd-4b62-81dd-4104c4ae8be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MenuUserCntrl1_RadMenu1&quot;)/ul[@class=&quot;rmRootGroup rmRoundedCorners rmShadows rmHorizontal&quot;]/li[@class=&quot;rmItem&quot;]/a[@class=&quot;rmLink rmRootLink rmExpand rmExpandDown&quot;]</value>
      <webElementGuid>32dbb906-2bfb-4a52-b698-56f1872d90f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_MenuUserCntrl1_RadMenu1']/ul/li[2]/a</value>
      <webElementGuid>922b412a-05c1-4d06-99ea-39a36af5b5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Agency')]</value>
      <webElementGuid>970db580-c0f5-421a-9264-ab435bb0e871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/following::a[1]</value>
      <webElementGuid>095401c8-4dd9-49dc-9970-34bbed88b53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log off'])[1]/following::a[2]</value>
      <webElementGuid>a149ec99-5305-41c7-8ac2-fd359e7553c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agency Details'])[1]/preceding::a[1]</value>
      <webElementGuid>00302ad1-aec8-47b6-ab1c-aea7f5a20ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidate Profile'])[1]/preceding::a[2]</value>
      <webElementGuid>50289cb0-f7aa-47f1-89f7-8769a4f15b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agency']/parent::*</value>
      <webElementGuid>3084dc5e-4943-4ab3-a25f-b2aded422c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/DashBoard.aspx#')]</value>
      <webElementGuid>98e693ed-537b-4ae0-8411-1b358069d85d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>948df786-6b50-451b-8d65-a84a2c169d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/DashBoard.aspx#' and (text() = 'Agency' or . = 'Agency')]</value>
      <webElementGuid>6197b1fe-1bd1-4c35-90de-042aa5ce46ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
